# Optional TLP drop-in: balanced profile
# Цель: компромисс между батареей и отзывчивостью.
# Не такой агрессивный как battery, и не такой прожорливый как performance.

CPU_ENERGY_PERF_POLICY_ON_AC=balance_performance
CPU_ENERGY_PERF_POLICY_ON_BAT=balance_power

CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0

PLATFORM_PROFILE_ON_AC=performance
PLATFORM_PROFILE_ON_BAT=balanced

WIFI_PWR_ON_AC=off
WIFI_PWR_ON_BAT=on

